source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
inhibit_all_warnings!

project 'GKValidator'
use_frameworks!

target 'GKValidator_Example' do
  pod "GKValidator", :path => "../"
end

target 'GKValidator_Tests' do
  pod "GKValidator", :path => "../"
  
end
